---

- name: Ensure Redis is present
  apt: pkg=redis-server state=latest
  become: true

- name: Ensure Redis Tools is present
  apt: pkg=redis-tools state=latest
  become: true

- name: Ensure Redis is started
  service: name=redis-server state=started enabled=yes
  become: true

- name: Ensure Redis Configuration
  template: src=redis.conf dest=/etc/redis/redis.conf owner=root group=root mode=0644
  become: true
  notify: Redis Restart