---
- name: Set php_ver variable to a default if not defined.
  set_fact:
    php_ver: 7.1
  when: php_ver is not defined

- name: Add PHP 7 PPA repository
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP CLI
  become: true
  apt:
    name: php{{ php_ver }}-cli
    state: latest

- name: Install PHP
  become: true
  apt: name=php{{ php_ver }} state=present

- name: Install required php packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - php{{ php_ver }}-mcrypt
    - php{{ php_ver }}-mbstring
    - php{{ php_ver }}-xml
    - php{{ php_ver }}-opcache
    - php{{ php_ver }}-gd
    - php{{ php_ver }}-intl
    - php{{ php_ver }}-curl
    - php{{ php_ver }}-json
    - php{{ php_ver }}-pgsql
    - php{{ php_ver }}-mysql
    - php{{ php_ver }}-sqlite3
    - php{{ php_ver }}-bcmath
    - php{{ php_ver }}-imagick

- name: Install PhpRedis extension
  become: true
  apt: "name=php-redis state=present"

- name: Enable the MCrypt extension
  become: true
  shell: phpenmod mcrypt

- name: Install php-fpm
  become: true
  apt: name=php{{ php_ver }}-fpm state=present

# - name: Install composer
#   shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  become: true
  shell: php -- --install-dir=/usr/local/bin --filename=composer
