---
- name: Add PHP 7 PPA repository
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP CLI
  become: true
  apt:
    name: php7.1-cli
    state: latest

- name: Install PHP
  become: true
  apt: name=php7.1 state=present

- name: Install required php packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - php7.1-mysql
    - php7.1-intl
    - php7.1-cli
    - php7.1-mcrypt
    - php7.1-mbstring

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer