---
- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: Upgrade installed packages
  become: true
  apt:
    upgrade: safe

- name: Install required base packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - curl
    - git
    - zip
    - unzip
    - nano
    - wget

# - name: Configure the timezone
#   become: true
#   template: src=timezone.tpl dest=/etc/timezone

# - name: More Configure the timezone
#   become: true
#   file: src=/usr/share/zoneinfo/UTC dest=/etc/localtime state=link force=yes backup=yes
