---
- name: Adding MongoDB Repo Key
  become: true
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
    state: "present"

- name: Adding MongoDB Apt Repo
  become: true
  apt_repository:
    repo: "deb https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse"
    state: "present"
    
- name: Installing MongoDB
  become: true
  apt:
    name: "mongodb-org"
    state: "present"